name: winbuild
on: [push]

jobs:
  job:
    name: ${{ matrix.os }}-hosted-pure
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx

    steps:
      - uses: actions/checkout@v2
        with:
          repository: Microsoft/vcpkg
      
      # On Windows runners, let's ensure to have the Developer Command Prompt environment setup correctly. As used here the Developer Command Prompt created is targeting x64 and using the default the Windows SDK.
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install qt5-declarative
        if: matrix.triplet == 'x64-windows'
        run: |
          subst V: ${{ github.workspace }} 
          cd V:
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install --triplet ${{ matrix.triplet }} qt5-declarative

      - name: Install ubuntu build deps
        if: matrix.triplet == 'x64-linux'
        run: |
          sudo apt-get install libx11-dev libxi-dev libxext-dev

      - name: Install osx build deps
        if: matrix.triplet == 'x64-osx'
        run: |
          brew install automake
          export CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include

      - name: Install qt5-declarative
        if: matrix.triplet != 'x64-windows'
        run: |
          echo $CPATH
          ./bootstrap-vcpkg.sh
          ./vcpkg install --triplet ${{ matrix.triplet }} qt5-svg
          rm -r -fo downloads
          rm -r -fo buildtrees
          ./vcpkg install --triplet ${{ matrix.triplet }} qt5-declarative
          
      - name: Debug x64-osx
        if: ${{ always() }}
        run: |
          cat /Users/runner/work/qt-for-vcpkg/qt-for-vcpkg/buildtrees/fontconfig/autoconf-x64-osx-out.log
          cat /Users/runner/work/qt-for-vcpkg/qt-for-vcpkg/buildtrees/fontconfig/autoconf-x64-osx-err.log

      - name: Debug x64-windows
        if: ${{ always() }}
        run: |
          cat "V:\buildtrees\qt5-declarative\package-build-x64-windows-dbg-out.log"
          cat "V:\buildtrees\qt5-declarative\package-build-x64-windows-dbg-err.log"
